# Site settings
title: OS2FleetOptimiser
subtitle: Optimering og grøn omstilling af de offentlige køretøjsflåder
email: sofbu@aarhus.dk
description: Den officielle hjemmeside for FleetOptimiser produktfællesskabet.
baseurl: "/websitefleetoptimiser" # the subpath of your site, e.g. /blog
url: "https://os2fleetoptimiser.github.io" # the base hostname & protocol for your site
author: Sofie Buhl
street_address: Bautavej 6
city: Aarhus V
state: TN
zip_code: 8210
country: Danmark
phone: (45) 4031 6815

# Social settings
github_url: https://github.com/OS2fleetoptimiser

# Build settings
markdown: kramdown
